import {Raleway, Roboto_Mono} from "next/font/google";
import "./globals.css";

const font = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ['400']
});

const fontMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ['400']
});

export const metadata = {
  title: "Ryuvi Tools",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} ${fontMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
